# Project 1 - Housing Prices Evaluation

- Method: DecisionTree + RandomForest
- Reference to: https://www.youtube.com/watch?v=wujyckteVYM&t=213s
- Data source: Kaggle.com

### 1. Problem definition
- Goal: Predict house price

In [1]:
import pandas as pd
import numpy as np

#### 1.1 PREPOCESSING DATA
- step 1. Import dataset

In [2]:
df = pd.read_csv("train.csv", sep = ",")
df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal     208500  
1         5   2007        WD         Normal     181500  
2         9   2008        WD         Normal     223500  
3         2   2006        WD        Abnorml     140000  
4        12   2008        WD         Normal     250000  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

In [57]:
# df.head(5)

- Step 2. Dataset overview

In [58]:
# df.shape

In [59]:
# df.info()

In [60]:
# list(df.columns)

In [61]:
# df.describe()

- Loc & iloc

In [62]:
# df.loc[(df.SalePrice == 755000) | (df.Street == "Pave")]

In [63]:
# df.loc[(df.SalePrice == 755000) & (df.Street == "Pave")]

In [64]:
# df.loc[(df.SalePrice == 755000) & (df.Street == "Pave"),['MSSubClass','SalePrice', 'Street']]

In [65]:
# df.iloc[[9]]

In [66]:
# df.iloc[1:10, :-75]

In [67]:
# x = df.iloc[1:10, :-1]
# y = df.iloc[1:3, -1]

- Data Manipulation

In [68]:
# df.SalePrice.dtype

In [69]:
# df.SalePrice.apply(lambda x : x.replace('$','')).dtype

### 2. Feature Selection
- Choose feature to train model
- Need to use 'feature engineering' to identify feature needed

In [70]:
needed_features =['LotArea','YearBuilt','1stFlrSF','2ndFlrSF','FullBath','BedroomAbvGr','TotRmsAbvGrd']

### 3. Spliting the datasets

In [71]:
x = df[needed_features]
y = df['SalePrice']

In [95]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
529    32668       1957      2515         0         3             4   
491     9490       1941       958       620         1             3   
459     7015       1950       979       224         1             3   
279    10005       1977      1156       866         2             4   
655     1680       1971       525       567         1             3   

     TotRmsAbvGrd  
529             9  
491             5  
459             5  
279             8  
655             6

In [73]:
#x_train.shape

In [74]:
#x_test.shape

In [75]:
#x.shape

### 4. Training Machine Learning Model
#### 4.1 Decision Tree Regressor

In [76]:
from sklearn.tree import DecisionTreeRegressor

In [77]:
dt_model = DecisionTreeRegressor(random_state=1)

In [78]:
dt_model.fit(x_train,y_train)

DecisionTreeRegressor(random_state=1)

In [79]:
y_train_pre = dt_model.predict(x_train.head())
y_test_pre = dt_model.predict(x_test.head())

In [80]:
y_test_pre

array([335000., 140200., 119000., 207500., 112000.])

In [113]:
pd.DataFrame({'y_test' : y_test.head(), 'y_test_pre': y_test_pre})

array([335000., 140200., 119000., 207500., 112000.])

#### 4.2 RandomForestRegressor

In [82]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

rf_model = RandomForestRegressor(random_state=1)
rf_model.fit(x_train, y_train)

RandomForestRegressor(random_state=1)

In [108]:
y_train_pre_rf = rf_model.predict(x_train.head())
y_test_pre_rf = rf_model.predict(x_test.head())

- predict with a new input

In [120]:
overview = x_test.head().copy()
overview['y_test_pre_rf'] = y_test_pre_rf
overview

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
529    32668       1957      2515         0         3             4   
491     9490       1941       958       620         1             3   
459     7015       1950       979       224         1             3   
279    10005       1977      1156       866         2             4   
655     1680       1971       525       567         1             3   

     TotRmsAbvGrd  y_test_pre_rf  
529             9       271690.0  
491             5       155039.0  
459             5       122024.0  
279             8       188915.0  
655             6        91147.0

In [44]:
rf_model.predict([[1000,1980,1200,900,2,3,8]])

C:\Users\Hien\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([177442.47])